name: Wize CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd backend && npm ci --dependencies
      - run: cd frontend && npm ci --dependencies
      - run: cd backend && npm run test
      - run: cd frontend && npm run build
      - run: cd backend && npm run build
      - run: pm2 restart wizeapp ./backend/dist/index.js
